# Generated by Django 3.1.7 on 2021-04-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCare_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caraouseldata',
            name='imgField',
        ),
        migrations.AddField(
            model_name='caraouseldata',
            name='imageUrl',
            field=models.URLField(default=False),
        ),
    ]
