# Generated by Django 3.1.7 on 2021-04-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCare_app', '0005_auto_20210420_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caraouseldata',
            name='image',
            field=models.URLField(default=True),
        ),
    ]
